# DockerFile MySQL sources:
# https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker/6211677-creez-un-fichier-docker-compose-pour-orchestrer-vos-conteneurs
# https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html

version: '3'
services:
  mysql_docker:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediscreen
      MYSQL_USER: mpatient
      MYSQL_PASSWORD: mpatient
    ports:
      - "3307:3306"
    
  mpatient:
    build:
      context: .
      target: mpatient
    depends_on:
      - mysql_docker
    restart: always
    ports:
      - "8081:8081"
      
  clientui:
    build:
      context: .
      target: clientui
    depends_on:
      - mpatient
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: {}